# Generated by Django 3.2.7 on 2021-10-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
    ]
